export const CONFIG_KEYS = {
  DATABASE_URI: 'DATABASE_URI',
  PASSWORD_HASH_SALT_ROUNDS: 'PASSWORD_HASH_SALT_ROUNDS',
  ACCESS_TOKEN_SIGN_KEY: 'ACCESS_TOKEN_SIGN_KEY',
  ACCESS_TOKEN_EXPIRES_IN: 'ACCESS_TOKEN_EXPIRES_IN',
};
